/**
 * Pixel art: the props the office is furnished with, as ASCII grids.
 *
 * The grids stay ASCII rather than becoming PNGs, and the cast does the opposite. The reason
 * is review, not consistency: one prop is 1,024 glyphs, which is a diff a person can read,
 * while the cast at 48×64 across a rig and three feature libraries is closer to a quarter of a
 * million, at which point a grid file stops being a review artifact and becomes a binary in
 * disguise. So furniture is authored here and people are authored in `cast/`.
 *
 * Redrawn at 32 for the daylight office. The 16×16 originals were a dark-room set — the whole
 * `ART` palette was chosen to sit against ink — and doubling them would have doubled the
 * pixels without adding any: at 32 a desk can have a monitor that reads as a monitor and a
 * plant can have leaves you can count.
 *
 * Grid contract, asserted by the tests:
 *   PROPS   32 rows x 32 columns, glyphs from ART plus '.'
 */

/**
 * Glyph to colour, for props. '.' is transparent and is not a key here.
 *
 * Two of these are deliberately the darkest values in the office. `#` and `k` are the
 * dove-blue family the art direction reserves for readable separation — an outline's job is
 * to hold a shape apart from what is behind it, and on a daylight floor that takes the
 * darkest value available rather than the lightest. Everything else is daylight.
 */
export const ART: Record<string, string> = {
  '#': '#1c2938', // 鸽蓝 — the outline that holds a shape together
  k: '#3a4557', // 鸽蓝, lifted — a softer edge and a contact line
  o: '#475164', // 鲸鱼灰 — structure and frames
  w: '#8a5a34', // 土色 — timber
  W: '#a8703f', // 土色, lit — a timber surface catching the light
  v: '#63421f', // 土色, deep — timber in shadow, and legs
  g: '#b8c8d6', // 远天蓝, shaded — moulded plastic and metal
  G: '#dfeaef', // 远天蓝 — the lit side of the same
  d: '#7d8f9e', // 星蓝, deepened — a darker fitting
  n: '#f7fbf9', // 月白, lifted — paper and screens
  N: '#fffef8', // 象牙白 — the brightest highlight there is
  b: '#2376b7', // 花青 — a screen, a spine, a cushion
  B: '#7aa7c8', // 星蓝 — the lit side of the same
  e: '#189c7b', // 竹绿 — foliage
  E: '#83cbac', // 粉绿 — foliage in the light
  r: '#aa6a4c', // 火泥棕 — terracotta and clay
  R: '#c98662', // 火泥棕, lit
  f: '#74759b', // 落电紫 — upholstery
  F: '#9a9bbb', // 落电紫, lit
}

/** Every glyph a prop may use. */
export const PROP_PALETTE = new Set(['.', ...Object.keys(ART)])

/**
 * The two glyphs permitted to be darker than the daylight floor.
 *
 * Named so "everything is daylight except the outline" is a property a test can state. Without
 * this the luminance rule would either have to exempt nothing — and forbid the separation the
 * art direction asks for — or exempt anything, which forbids nothing.
 */
export const OUTLINE_GLYPHS = new Set(['#', 'k'])

/** Props are 32x32 and drawn at one tile each. */
export const PROPS: Record<string, string[]> = {
  desk: [
    '................................',
    '................................',
    '................................',
    '................................',
    '........##############..........',
    '........#GGGGGGGGGGGG#..........',
    '........#GbbbbbbbbbbG#..........',
    '........#GbBBBBBBBBbG#..........',
    '........#GbBnnnnnnBbG#..........',
    '........#GbBnnnnnnBbG#..........',
    '........#GbBnnnnnnBbG#..........',
    '........#GbBBBBBBBBbG#..........',
    '........#GbbbbbbbbbbG#..........',
    '........#GGGGGGGGGGGG#..........',
    '........##############..........',
    '............#dddd#.....#RRR#....',
    '............#dddd#.....#rrr#....',
    '..........###########..#####....',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwnnnnnnnnnnnnnnwwwwwwwwwwwwww',
    'wwwwnnnnnnnnnnnnnnwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
    '....v......................v....',
    '....v......................v....',
    '....v......................v....',
    '....v......................v....',
    '....v......................v....',
    '....v......................v....',
    '....k......................k....',
    '................................',
  ],
  chair: [
    '................................',
    '................................',
    '................................',
    '..........############..........',
    '.........#ffffffffffff#.........',
    '.........#fFFFFFFFFFFf#.........',
    '.........#fFFFFFFFFFFf#.........',
    '.........#fFFFFFFFFFFf#.........',
    '.........#fFFFFFFFFFFf#.........',
    '.........#fFFFFFFFFFFf#.........',
    '.........#ffffffffffff#.........',
    '..........############..........',
    '..............oooo..............',
    '..............oooo..............',
    '.......##################.......',
    '......#ffffffffffffffffff#......',
    '......#fFFFFFFFFFFFFFFFFf#......',
    '......#fFFFFFFFFFFFFFFFFf#......',
    '......#ffffffffffffffffff#......',
    '.......##################.......',
    '..............oooo..............',
    '..............oooo..............',
    '..............oooo..............',
    '..........#############.........',
    '.........#o..........o#.........',
    '........#o............o#........',
    '.......#o..............o#.......',
    '.......o................o.......',
    '......gg................gg......',
    '......gg................gg......',
    '......kk................kk......',
    '................................',
  ],
  plant: [
    '................................',
    '..............ee................',
    '...........e..ee..e.............',
    '..........eEe.ee.eEe............',
    '.........eEEEeeeeEEEe...........',
    '........eEEEEEeeEEEEEe..........',
    '.......eEEEEEEeeEEEEEEe.........',
    '......eEEEEEEEeeEEEEEEEe........',
    '.....eEEEEEEEEeeEEEEEEEEe.......',
    '......eEEEEEEEeeEEEEEEEe........',
    '.......eEEEEEEeeEEEEEEe.........',
    '........eEEEEEeeEEEEEe..........',
    '.........eEEEEeeEEEEe...........',
    '..........eEEEeeEEEe............',
    '...........eEEeeEEe.............',
    '............eeeeee..............',
    '..............ee................',
    '..............ee................',
    '..............ee................',
    '..............ee................',
    '..........##########............',
    '..........#RRRRRRRR#............',
    '..........#RrrrrrrR#............',
    '..........#rrrrrrrr#............',
    '..........#rrrrrrrr#............',
    '...........#rrrrrr#.............',
    '...........#rrrrrr#.............',
    '............#rrrr#..............',
    '............######..............',
    '............kkkkkk..............',
    '................................',
    '................................',
  ],
  sofaL: [
    '................................',
    '................................',
    '................................',
    '..........######################',
    '.........#ffffffffffffffffffffff',
    '.........#fFFFFFFFFFFFFFFFFFFFFF',
    '.........#fFFFFFFFFFFFFFFFFFFFFF',
    '.........#fFFFFFFFFFFFFFFFFFFFFF',
    '.........#fFFFFFFFFFFFFFFFFFFFFF',
    '.........#fFFFFFFFFFFFFFFFFFFFFF',
    '.........#ffffffffffffffffffffff',
    '.........#f####################o',
    '.........#fFFFFFFFFFFFFFFFFFFFFF',
    '.........#fFFFFFFFFFFFFFFFFFFFFF',
    '.........#fFFFFFFFFFFFFFFFFFFFFF',
    '.........#fFFFFFFFFFFFFFFFFFFFFF',
    '.........#fFFFFFFFFFFFFFFFFFFFFF',
    '.........#fFFFFFFFFFFFFFFFFFFFFF',
    '.........#fFFFFFFFFFFFFFFFFFFFFF',
    '.........#ffffffffffffffffffffff',
    '.........#f####################o',
    '.........#ffffffffffffffffffffff',
    '.........#ffffffffffffffffffffff',
    '.........#######################',
    '..........##....................',
    '..........vv..................vv',
    '..........vv..................vv',
    '..........kk..................kk',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
  sofaR: [
    '................................',
    '................................',
    '................................',
    '######################..........',
    'fffffffffffffffffffffff#........',
    'FFFFFFFFFFFFFFFFFFFFFff#........',
    'FFFFFFFFFFFFFFFFFFFFFff#........',
    'FFFFFFFFFFFFFFFFFFFFFff#........',
    'FFFFFFFFFFFFFFFFFFFFFff#........',
    'FFFFFFFFFFFFFFFFFFFFFff#........',
    'fffffffffffffffffffffff#........',
    'o####################ff#........',
    'FFFFFFFFFFFFFFFFFFFFFff#........',
    'FFFFFFFFFFFFFFFFFFFFFff#........',
    'FFFFFFFFFFFFFFFFFFFFFff#........',
    'FFFFFFFFFFFFFFFFFFFFFff#........',
    'FFFFFFFFFFFFFFFFFFFFFff#........',
    'FFFFFFFFFFFFFFFFFFFFFff#........',
    'FFFFFFFFFFFFFFFFFFFFFff#........',
    'fffffffffffffffffffffff#........',
    'o####################ff#........',
    'fffffffffffffffffffffff#........',
    'fffffffffffffffffffffff#........',
    '########################........',
    '....................##..........',
    'vv..................vv..........',
    'vv..................vv..........',
    'kk..................kk..........',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
  table: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwWWWWWWWWWWWWWWWWwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwWWWWWWWWWWWWWWWWwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
    'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  ],
  shelf: [
    '................................',
    '..############################..',
    '..#WWWWWWWWWWWWWWWWWWWWWWWWWW#..',
    '..#wwwwwwwwwwwwwwwwwwwwwwwwww#..',
    '..#w#b#e#r#b#..#n#b#e#n#r#b#w#..',
    '..#w#b#e#r#b#..#n#b#e#n#r#b#w#..',
    '..#w#b#e#r#b#..#n#b#e#n#r#b#w#..',
    '..#w#B#E#R#B#..#N#B#E#N#R#B#w#..',
    '..#wwwwwwwwwwwwwwwwwwwwwwwwww#..',
    '..#WWWWWWWWWWWWWWWWWWWWWWWWWW#..',
    '..#wwwwwwwwwwwwwwwwwwwwwwwwww#..',
    '..#w#n#b#n#e#r#..#b#e#r#n#b#w#..',
    '..#w#n#b#n#e#r#..#b#e#r#n#b#w#..',
    '..#w#n#b#n#e#r#..#b#e#r#n#b#w#..',
    '..#w#N#B#N#E#R#..#B#E#R#N#B#w#..',
    '..#wwwwwwwwwwwwwwwwwwwwwwwwww#..',
    '..#WWWWWWWWWWWWWWWWWWWWWWWWWW#..',
    '..#wwwwwwwwwwwwwwwwwwwwwwwwww#..',
    '..#w#e#r#b#n#..#e#n#b#r#e#b#w#..',
    '..#w#e#r#b#n#..#e#n#b#r#e#b#w#..',
    '..#w#e#r#b#n#..#e#n#b#r#e#b#w#..',
    '..#w#E#R#B#N#..#E#N#B#R#E#B#w#..',
    '..#wwwwwwwwwwwwwwwwwwwwwwwwww#..',
    '..#WWWWWWWWWWWWWWWWWWWWWWWWWW#..',
    '..#wwwwwwwwwwwwwwwwwwwwwwwwww#..',
    '..#wwwwwwwwwwwwwwwwwwwwwwwwww#..',
    '..############################..',
    '...#v#....................#v#...',
    '...#v#....................#v#...',
    '...#v#....................#v#...',
    '...kkk....................kkk...',
    '................................',
  ],
  board: [
    '................................',
    '..oooooooooooooooooooooooooooo..',
    '..oNNNNNNNNNNNNNNNNNNNNNNNNNNo..',
    '..oNNNNNNNNNNNNNNNNNNNNNNNNNNo..',
    '..oNNbbbbbNNNNNNNNNNNNNNNNNNNo..',
    '..oNNNNNNNNNNNNbbbbbbNNNNNNNNo..',
    '..oNNNNNNNNNNNNNNNNNNNNNNNNNNo..',
    '..oNNNNbbbNNNNNNNNNNNNeeeeeNNo..',
    '..oNNNNNNNNNNNNNNNNNNNNNNNNNNo..',
    '..oNNNNNNNNNbbbbbbbNNNNNNNNNNo..',
    '..oNNNNNNNNNNNNNNNNNNNNNNNNNNo..',
    '..oNNeeeeNNNNNNNNNNNNNNbbbbNNo..',
    '..oNNNNNNNNNNNNNNNNNNNNNNNNNNo..',
    '..oNNNNNNNNbbbbbNNNNNNNNNNNNNo..',
    '..oNNNNNNNNNNNNNNNNNNNNNNNNNNo..',
    '..oNNNNNNNNNNNNNNNNNNNNNNNNNNo..',
    '..oNNNNNNNNNNNNNNNNNNNNNNNNNNo..',
    '..oNNNNNNNNNNNNNNNNNNNNNNNNNNo..',
    '..oNNNNNNNNNNNNNNNNNNNNNNNNNNo..',
    '..oNNNNNNNNNNNNNNNNNNNNNNNNNNo..',
    '..oooooooooooooooooooooooooooo..',
    '..ogggggggggggggggggggggggggo...',
    '................................',
    '..........g..........g..........',
    '..........g..........g..........',
    '..........g..........g..........',
    '..........g..........g..........',
    '.........gg..........gg.........',
    '.........gg..........gg.........',
    '........ggg..........ggg........',
    '........kkk..........kkk........',
    '................................',
  ],
  cooler: [
    '................................',
    '............########............',
    '...........#gBBBBBBg#...........',
    '..........#gBBBBBBBBg#..........',
    '..........#gBBBBBBBBg#..........',
    '..........#gBBBBBBBBg#..........',
    '..........#gBBBBBBBBg#..........',
    '..........#gBBBBBBBBg#..........',
    '..........#gBBBBBBBBg#..........',
    '...........#gBBBBBBg#...........',
    '............#gBBBBg#............',
    '.............#gBBg#.............',
    '..........############..........',
    '..........#GGGGGGGGGG#..........',
    '..........#GnnnnnnnnG#..........',
    '..........#GnnnnnnnnG#..........',
    '..........#GnnnnnnnnG#..........',
    '..........#Gnn####nnG#..........',
    '..........#Gnn#..#nnG#..........',
    '..........#Gnn####nnG#..........',
    '..........#GnnnnnnnnG#..........',
    '..........#GnnnnnnnnG#..........',
    '..........#GnnnnnnnnG#..........',
    '..........#GGGGGGGGGG#..........',
    '..........############..........',
    '..........#gggggggggg#..........',
    '..........############..........',
    '...........k........k...........',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
  coffee: [
    '................................',
    '................................',
    '..........############..........',
    '..........#oooooooooo#..........',
    '..........#odddddddddo#.........',
    '..........#odnnnnnnndo#.........',
    '..........#odnnnnnnndo#.........',
    '..........#odddddddddo#.........',
    '..........#oooooooooo#..........',
    '..........############..........',
    '..........#oooooooooo#..........',
    '..........#o########o#..........',
    '..........#o#......#o#..........',
    '..........#o#......#o#..........',
    '..........#o#.rrrr.#o#..........',
    '..........#o#.rRRr.#o#..........',
    '..........#o#.rrrr.#o#..........',
    '..........#o#.####.#o#..........',
    '..........#o#......#o#..........',
    '..........#o########o#..........',
    '..........#oooooooooo#..........',
    '..........############..........',
    '..........#gggggggggg#..........',
    '..........#gNNNNNNNNg#..........',
    '..........#gggggggggg#..........',
    '..........############..........',
    '...........kkkkkkkkkk...........',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
  art: [
    '................................',
    '................................',
    '....########################....',
    '....#WWWWWWWWWWWWWWWWWWWWWW#....',
    '....#wNNNNNNNNNNNNNNNNNNNNw#....',
    '....#wNNNNNNNNNNNNNNNNNNNNw#....',
    '....#wNNBBBBBBBBBBBBBBBBNNw#....',
    '....#wNNBBBBBBBBBBBBBBBBNNw#....',
    '....#wNNBBBBBBBBBBBBBBBBNNw#....',
    '....#wNNBBBBBBBBBBBBBBBBNNw#....',
    '....#wNNBBBBBBBBBBBBBBBBNNw#....',
    '....#wNNBBBBBBBBBBEEBBBBNNw#....',
    '....#wNNBBBBBBBBBeeeeBBBBNw#....',
    '....#wNNBBBBBBBBeeeeeeBBBNw#....',
    '....#wNNBBBBBBBeeeeeeeeBBNw#....',
    '....#wNNBBBBBBeeeeeeeeeeBNw#....',
    '....#wNNBBBBBeeeeeeeeeeeeNw#....',
    '....#wNNBBBBeeeeeeeeeeeeeNw#....',
    '....#wNNNNNNNNNNNNNNNNNNNNw#....',
    '....#wNNNNNNNNNNNNNNNNNNNNw#....',
    '....#wwwwwwwwwwwwwwwwwwwwww#....',
    '....########################....',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
  pinboard: [
    '................................',
    '..############################..',
    '..#wwwwwwwwwwwwwwwwwwwwwwwwww#..',
    '..#wRRRRRRRRRRRRRRRRRRRRRRRRw#..',
    '..#wRnnnnRRRRRRnnnnnRRRRRRRRw#..',
    '..#wRnnnnRRRRRRnnnnnRRRRRRRRw#..',
    '..#wRnnnnRRRRRRnnnnnRRRRRRRRw#..',
    '..#wRnnnnRRRRRRnnnnnRRRRRRRRw#..',
    '..#wRRRRRRRRRRRRRRRRRRRRRRRRw#..',
    '..#wRRRRRRRRRRRRRRRRRnnnnnnRw#..',
    '..#wRRnnnnnnRRRRRRRRRnnnnnnRw#..',
    '..#wRRnnnnnnRRRRRRRRRnnnnnnRw#..',
    '..#wRRnnnnnnRRRRRRRRRnnnnnnRw#..',
    '..#wRRnnnnnnRRRRRRRRRRRRRRRRw#..',
    '..#wRRnnnnnnRRRRRRRRRRRRRRRRw#..',
    '..#wRRRRRRRRRRRRnnnnnRRRRRRRw#..',
    '..#wRRRRRRRRRRRRnnnnnRRRRRRRw#..',
    '..#wRRnnnnRRRRRRnnnnnRRRRRRRw#..',
    '..#wRRnnnnRRRRRRRRRRRRRRRRRRw#..',
    '..#wRRRRRRRRRRRRRRRRRRRRRRRRw#..',
    '..#wwwwwwwwwwwwwwwwwwwwwwwwww#..',
    '..############################..',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
  floorplant: [
    '................................',
    '...............e................',
    '..........e....e....e...........',
    '.........eEe..eEe..eEe..........',
    '........eEEEeeEEEeeEEEe.........',
    '.......eEEEEEEEEEEEEEEEe........',
    '......eEEEEEEEEEEEEEEEEEe.......',
    '.....eEEEEEEEEEEEEEEEEEEEe......',
    '....eEEEEEEEEEEEEEEEEEEEEEe.....',
    '.....eEEEEEEEEEEEEEEEEEEEe......',
    '......eEEEEEEEEEEEEEEEEEe.......',
    '.......eEEEEEEEEEEEEEEEe........',
    '........eEEEEEEEEEEEEEe.........',
    '.........eEEEEEEEEEEEe..........',
    '..........eEEEEEEEEEe...........',
    '...........eEEEEEEEe............',
    '............eEEEEEe.............',
    '.............eeeee..............',
    '..............eee...............',
    '..............eee...............',
    '.........############...........',
    '.........#RRRRRRRRRR#...........',
    '.........#RrrrrrrrrR#...........',
    '.........#rrrrrrrrrr#...........',
    '.........#rrrrrrrrrr#...........',
    '..........#rrrrrrrr#............',
    '..........#rrrrrrrr#............',
    '..........#rrrrrrrr#............',
    '...........########.............',
    '...........kkkkkkkk.............',
    '................................',
    '................................',
  ],
  coffeetable: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '......................##........',
    '.....................#nn#.......',
    '...####..............#nn#.......',
    '...#bb#..............#NN#.......',
    '...#bb#..............####.......',
    '...####.........................',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
    '..v..........................v..',
    '..v..........................v..',
    '..v..........................v..',
    '..v..........................v..',
    '..v..........................v..',
    '..v..........................v..',
    '..k..........................k..',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
  stool: [
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '.........################.......',
    '........#ffffffffffffffff#......',
    '........#fFFFFFFFFFFFFFFf#......',
    '........#fFFFFFFFFFFFFFFf#......',
    '........#ffffffffffffffff#......',
    '.........################.......',
    '..........oo........oo..........',
    '..........oo........oo..........',
    '..........oo........oo..........',
    '..........oo########oo..........',
    '..........oo........oo..........',
    '..........oo........oo..........',
    '.........oo..........oo.........',
    '.........oo..........oo.........',
    '........oo............oo........',
    '........oo............oo........',
    '.......oo..............oo.......',
    '.......oo..............oo.......',
    '.......kk..............kk.......',
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
  ],
  lamp: [
    '................................',
    '..........############..........',
    '.........#NNNNNNNNNNNN#.........',
    '........#NNNNNNNNNNNNNN#........',
    '.......#NNNNNNNNNNNNNNNN#.......',
    '.......##################.......',
    '..........#GGGGGGGGGG#..........',
    '..............oooo..............',
    '..............oooo..............',
    '..............oooo..............',
    '..............oooo..............',
    '..............oooo..............',
    '..............oooo..............',
    '..............oooo..............',
    '..............oooo..............',
    '..............oooo..............',
    '..............oooo..............',
    '..............oooo..............',
    '..............oooo..............',
    '..............oooo..............',
    '..............oooo..............',
    '..............oooo..............',
    '..............oooo..............',
    '..............oooo..............',
    '..............oooo..............',
    '...........##########...........',
    '..........#gggggggggg#..........',
    '..........#GGGGGGGGGG#..........',
    '..........############..........',
    '...........kkkkkkkkkk...........',
    '................................',
    '................................',
  ],
}

// =========================================================================
// The cast, still on the prototype's grids
// =========================================================================

/**
 * The 10×16 character art the prototype drew, unchanged.
 *
 * Still here, and still 16 pixels tall in a 32-pixel tile, because the redesign replaces the
 * cast wholesale rather than scaling it — a person is a 48×64 layered rig in `cast/`, not a
 * bigger version of this. Until that lands the renderer draws these at 2× so nobody shrinks
 * in the meantime, and when it lands this section and everything that reads it goes.
 *
 * Grid contract, asserted by the tests:
 *   BODY       14 rows x 10 columns, glyphs from the character palette
 *   LEGS       2 rows x 10 columns  (14 + 2 = the 16-row character)
 *   LONG_HAIR  14 rows x 10 columns
 */

/** The character palette. Body, legs and hair glyphs must all come from this set. */
export const CHARACTER_PALETTE = new Set([
  '.', 'j', 'h', 'H', 'l', 's', 'S', 'e', 'c', 'u', 't', 'T', 'p', 'P', 'b', 'B',
])

/** Character bodies: 14 rows, with legs supplying the last 2. */
export const BODY: Record<string, string[]> = {
  "down": [
    "...hhhh...",
    "..hhhhhh..",
    ".hhhhhhhh.",
    ".hhHHHHhh.",
    ".hssssssh.",
    ".hsessesh.",
    ".hssccssh.",
    "..lssssl..",
    ".uttttttu.",
    ".uttttttu.",
    ".uttttttu.",
    ".usttttsu.",
    ".uTTTTTTu.",
    ".uppppppu.",
  ],
  "up": [
    "...hhhh...",
    "..hhhhhh..",
    ".hhhhhhhh.",
    ".hhHHHHhh.",
    ".hhhhhhhh.",
    ".hhhhhhhh.",
    ".hhhhhhhh.",
    "..jhhhhj..",
    ".uttttttu.",
    ".uttttttu.",
    ".uttttttu.",
    ".usttttsu.",
    ".uTTTTTTu.",
    ".uppppppu.",
  ],
  "side": [
    "...hhhh...",
    "..hhhhhh..",
    ".hhhhhhhh.",
    ".hhhHHHhh.",
    ".hhlsssss.",
    ".hhssesss.",
    ".hhscssss.",
    "..lssssl..",
    ".uttttttu.",
    ".uttttttu.",
    ".uttttttu.",
    ".utttttts.",
    ".uTTTTTTu.",
    ".uppppppu.",
  ],
}

/** Three walk frames of legs, 2 rows each. */
export const LEGS: string[][] = [
  [
    ".upp..ppu.",
    ".ubb..bbu.",
  ],
  [
    ".pp....pp.",
    ".bb....bb.",
  ],
  [
    "...pppp...",
    "...bbbb...",
  ],
]

/** Optional long hair, overlaid on a body. */
export const LONG_HAIR: Record<string, string[]> = {
  "front": [
    "..........",
    "..........",
    "..........",
    "..........",
    "..........",
    "..........",
    "..........",
    ".hh....hh.",
    ".hh....hh.",
    ".hh....hh.",
    "..h....h..",
    "..........",
    "..........",
    "..........",
  ],
  "side": [
    "..........",
    "..........",
    "..........",
    "..........",
    "..........",
    "..........",
    "..........",
    ".hh.......",
    ".hh.......",
    ".hh.......",
    "..h.......",
    "..........",
    "..........",
    "..........",
  ],
}
