/**
 * Pixel art: sprite sheets built at runtime from ASCII grids.
 *
 * Ported from script section 8 of `company-os.html` (`:1899`). The grids are extracted
 * mechanically rather than retyped — a transposed glyph would be invisible in review and would
 * show up as one wrong pixel on one frame, so authorship is not the useful thing here. Exactness
 * is, and `sprites.test.ts` re-runs the same validation the prototype's own `test/sprites.js`
 * applies (R33: sprite-grid validation is retained alongside the ported renderer).
 *
 * The palettes are derived per id, so no avatar assets exist and nobody's likeness is used — see
 * `palette.ts` for the derivation, which the golden vectors pin against the kernel.
 *
 * Grid contract, asserted by the tests:
 *   PROPS      16 rows x 16 columns, glyphs from ART plus '.'
 *   BODY       14 rows x 10 columns, glyphs from the character palette
 *   LEGS       2 rows x 10 columns  (14 + 2 = the 16-row character)
 *   LONG_HAIR  14 rows x 10 columns
 */

/** Glyph to colour, for props. '.' is transparent and is not a key here. */
export const ART: Record<string, string> = {
  "#": "#20242e",
  "o": "#39404f",
  "w": "#8a5a3b",
  "W": "#a5714b",
  "v": "#63402c",
  "g": "#7d8698",
  "G": "#a3adbe",
  "d": "#4e5666",
  "n": "#dfe5ee",
  "N": "#f6f8fb",
  "b": "#2f5bd0",
  "B": "#7fa4ff",
  "e": "#2e7d50",
  "E": "#48a86c",
  "r": "#a4552a",
  "R": "#c06d3d",
  "f": "#3f5b8c",
  "F": "#5379b5",
  "k": "#171a21"
};

/** The character palette. Body, legs and hair glyphs must all come from this set. */
export const CHARACTER_PALETTE = new Set([
  '.', 'j', 'h', 'H', 'l', 's', 'S', 'e', 'c', 'u', 't', 'T', 'p', 'P', 'b', 'B',
])

/** Props are 16x16 and drawn at one tile each. */
export const PROPS: Record<string, string[]> = {
  "desk": [
    "................",
    "................",
    ".....######.....",
    ".....#gGGg#.....",
    ".....#bBBb#.....",
    ".....#bBBb#.....",
    ".....#gggg#.....",
    ".......##.......",
    "......dggd......",
    "WWWWWWWWWWWWWWWW",
    "wwwwnnnnnnwwwwww",
    "wwwwwwwwwwwwwwww",
    "vvvvvvvvvvvvvvvv",
    "..v..........v..",
    "..v..........v..",
    "..k..........k..",
  ],
  "chair": [
    "................",
    "................",
    "................",
    "................",
    ".....dddddd.....",
    "....dggggggd....",
    "....dgGGGGgd....",
    "....dggggggd....",
    "....dddddddd....",
    ".....dddddd.....",
    ".......gg.......",
    ".....g#gg#g.....",
    ".....gg..gg.....",
    "................",
    "................",
    "................",
  ],
  "plant": [
    "................",
    "................",
    "......e..e......",
    ".....eEeeEe.....",
    "....eEEEEEEe....",
    "...eEEEEEEEEe...",
    "....eEEEEEEe....",
    ".....eEEEEe.....",
    "......eEEe......",
    ".......ee.......",
    ".......ee.......",
    ".....oRRRRo.....",
    ".....orrrro.....",
    ".....orrrro.....",
    "......oooo......",
    "................",
  ],
  "sofaL": [
    "................",
    "................",
    ".....ooooooooooo",
    "....offfffffffff",
    "....offFFFFFFFFF",
    "....offFFFFFFFFF",
    "....offFFFFFFFFF",
    "....offfffffffff",
    "....offFFFFFFFFF",
    "....offFFFFFFFFF",
    "....offFFFFFFFFF",
    "....offfffffffff",
    "....oooooooooooo",
    ".....k.........k",
    "................",
    "................",
  ],
  "sofaR": [
    "................",
    "................",
    "ooooooooooo.....",
    "fffffffffffo....",
    "FFFFFFFFFffo....",
    "FFFFFFFFFffo....",
    "FFFFFFFFFffo....",
    "fffffffffffo....",
    "FFFFFFFFFffo....",
    "FFFFFFFFFffo....",
    "FFFFFFFFFffo....",
    "fffffffffffo....",
    "oooooooooooo....",
    "k.........k.....",
    "................",
    "................",
  ],
  "table": [
    "wwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwww",
    "WWWWWWWWWWWWWWWW",
    "wwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwww",
    "WWWWWWWWWWWWWWWW",
    "wwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwww",
  ],
  "shelf": [
    "................",
    ".oooooooooooooo.",
    ".ovvvvvvvvvvvvo.",
    ".ovnnvnnvnnvnvo.",
    ".ovnnvnnvnnvnvo.",
    ".ovvvvvvvvvvvvo.",
    ".ovnnvnnvnnvnvo.",
    ".ovnnvnnvnnvnvo.",
    ".ovvvvvvvvvvvvo.",
    ".ovnnvnbbvnnvvo.",
    ".ovnnvnbbvnnvvo.",
    ".ovvvvvvvvvvvvo.",
    ".oooooooooooooo.",
    "..o............o",
    "................",
    "................",
  ],
  "board": [
    "................",
    ".##############.",
    ".#NNNNNNNNNNNN#.",
    ".#NbbbNNNNNNNN#.",
    ".#NNNNNNNbbbNN#.",
    ".#NNbbNNNNNNNN#.",
    ".#NNNNNNNNbbNN#.",
    ".#NNNNbbNNNNNN#.",
    ".#NNNNNNNNNNNN#.",
    ".##############.",
    ".....g....g.....",
    ".....g....g.....",
    ".....g....g.....",
    "....gg....gg....",
    "................",
    "................",
  ],
  "cooler": [
    "................",
    "......oooo......",
    ".....oBBBBo.....",
    ".....oBBBBo.....",
    ".....oBBBBo.....",
    "......oBBo......",
    ".....onnnno.....",
    ".....onnnno.....",
    ".....on..no.....",
    ".....onnnno.....",
    ".....onnnno.....",
    ".....onnnno.....",
    ".....oooooo.....",
    ".....k....k.....",
    "................",
    "................",
  ],
  "coffee": [
    "................",
    ".....######.....",
    ".....#dddd#.....",
    ".....#dnnd#.....",
    ".....#dnnd#.....",
    ".....#dddd#.....",
    ".....#d##d#.....",
    ".....#dNNd#.....",
    ".....#dNNd#.....",
    ".....#dddd#.....",
    ".....######.....",
    ".....gggggg.....",
    ".....gggggg.....",
    "......oooo......",
    "................",
    "................",
  ],
}

/** Character bodies: 14 rows, with legs supplying the last 2. */
export const BODY: Record<string, string[]> = {
  "down": [
    "...hhhh...",
    "..hhhhhh..",
    ".hhhhhhhh.",
    ".hhHHHHhh.",
    ".hssssssh.",
    ".hsessesh.",
    ".hssccssh.",
    "..lssssl..",
    ".uttttttu.",
    ".uttttttu.",
    ".uttttttu.",
    ".usttttsu.",
    ".uTTTTTTu.",
    ".uppppppu.",
  ],
  "up": [
    "...hhhh...",
    "..hhhhhh..",
    ".hhhhhhhh.",
    ".hhHHHHhh.",
    ".hhhhhhhh.",
    ".hhhhhhhh.",
    ".hhhhhhhh.",
    "..jhhhhj..",
    ".uttttttu.",
    ".uttttttu.",
    ".uttttttu.",
    ".usttttsu.",
    ".uTTTTTTu.",
    ".uppppppu.",
  ],
  "side": [
    "...hhhh...",
    "..hhhhhh..",
    ".hhhhhhhh.",
    ".hhhHHHhh.",
    ".hhlsssss.",
    ".hhssesss.",
    ".hhscssss.",
    "..lssssl..",
    ".uttttttu.",
    ".uttttttu.",
    ".uttttttu.",
    ".utttttts.",
    ".uTTTTTTu.",
    ".uppppppu.",
  ],
}

/** Three walk frames of legs, 2 rows each. */
export const LEGS: string[][] = [
  [
    ".upp..ppu.",
    ".ubb..bbu.",
  ],
  [
    ".pp....pp.",
    ".bb....bb.",
  ],
  [
    "...pppp...",
    "...bbbb...",
  ],
]

/** Optional long hair, overlaid on a body. */
export const LONG_HAIR: Record<string, string[]> = {
  "front": [
    "..........",
    "..........",
    "..........",
    "..........",
    "..........",
    "..........",
    "..........",
    ".hh....hh.",
    ".hh....hh.",
    ".hh....hh.",
    "..h....h..",
    "..........",
    "..........",
    "..........",
  ],
  "side": [
    "..........",
    "..........",
    "..........",
    "..........",
    "..........",
    "..........",
    "..........",
    ".hh.......",
    ".hh.......",
    ".hh.......",
    "..h.......",
    "..........",
    "..........",
    "..........",
  ],
}

/** Every glyph a prop may use. */
export const PROP_PALETTE = new Set(['.', ...Object.keys(ART)])
