# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.grpc import agents_pb2 as agents__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agents_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentResolverStub(object):
    """Phase 2's agent layer. Phase 1 ships a stub resolver whose only job is to prove
    the pending-input contract works before Phase 2 depends on it.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Resolve = channel.stream_stream(
                '/companyos.agents.v1.AgentResolver/Resolve',
                request_serializer=agents__pb2.Resolution.SerializeToString,
                response_deserializer=agents__pb2.Decision.FromString,
                _registered_method=True)


class AgentResolverServicer(object):
    """Phase 2's agent layer. Phase 1 ships a stub resolver whose only job is to prove
    the pending-input contract works before Phase 2 depends on it.
    """

    def Resolve(self, request_iterator, context):
        """Opened by the kernel (R17), same shape and for the same reasons as the domain
        consult stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentResolverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Resolve': grpc.stream_stream_rpc_method_handler(
                    servicer.Resolve,
                    request_deserializer=agents__pb2.Resolution.FromString,
                    response_serializer=agents__pb2.Decision.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'companyos.agents.v1.AgentResolver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('companyos.agents.v1.AgentResolver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentResolver(object):
    """Phase 2's agent layer. Phase 1 ships a stub resolver whose only job is to prove
    the pending-input contract works before Phase 2 depends on it.
    """

    @staticmethod
    def Resolve(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/companyos.agents.v1.AgentResolver/Resolve',
            agents__pb2.Resolution.SerializeToString,
            agents__pb2.Decision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
