# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agents.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agents.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61gents.proto\x12\x13\x63ompanyos.agents.v1\"\xa2\x01\n\nResolution\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\x12\x16\n\x0eraised_at_tick\x18\x03 \x01(\x04\x12\x13\n\x0bowning_item\x18\x04 \x01(\t\x12\x15\n\rcheckpoint_id\x18\x05 \x01(\t\x12\x19\n\x11permitted_options\x18\x06 \x03(\t\x12\x11\n\trules_ver\x18\x07 \x01(\t\"\xf7\x01\n\x08\x44\x65\x63ision\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x15\n\rchosen_option\x18\x02 \x01(\t\x12\x37\n\x08resolver\x18\x03 \x01(\x0b\x32%.companyos.agents.v1.ResolverIdentity\x12\x11\n\trules_ver\x18\x04 \x01(\t\x12\x41\n\nprovenance\x18\x05 \x03(\x0b\x32-.companyos.agents.v1.Decision.ProvenanceEntry\x1a\x31\n\x0fProvenanceEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xbb\x01\n\x10ResolverIdentity\x12\x38\n\x04kind\x18\x01 \x01(\x0e\x32*.companyos.agents.v1.ResolverIdentity.Kind\x12\x10\n\x08identity\x18\x02 \x01(\t\"[\n\x04Kind\x12\x14\n\x10KIND_UNSPECIFIED\x10\x00\x12\x13\n\x0fHUMAN_IN_PERSON\x10\x01\x12\x13\n\x0fHUMAN_FROM_TRAY\x10\x02\x12\t\n\x05\x41GENT\x10\x03\x12\x08\n\x04STUB\x10\x04\x32^\n\rAgentResolver\x12M\n\x07Resolve\x12\x1f.companyos.agents.v1.Resolution\x1a\x1d.companyos.agents.v1.Decision(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agents_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DECISION_PROVENANCEENTRY']._loaded_options = None
  _globals['_DECISION_PROVENANCEENTRY']._serialized_options = b'8\001'
  _globals['_RESOLUTION']._serialized_start=38
  _globals['_RESOLUTION']._serialized_end=200
  _globals['_DECISION']._serialized_start=203
  _globals['_DECISION']._serialized_end=450
  _globals['_DECISION_PROVENANCEENTRY']._serialized_start=401
  _globals['_DECISION_PROVENANCEENTRY']._serialized_end=450
  _globals['_RESOLVERIDENTITY']._serialized_start=453
  _globals['_RESOLVERIDENTITY']._serialized_end=640
  _globals['_RESOLVERIDENTITY_KIND']._serialized_start=549
  _globals['_RESOLVERIDENTITY_KIND']._serialized_end=640
  _globals['_AGENTRESOLVER']._serialized_start=642
  _globals['_AGENTRESOLVER']._serialized_end=736
# @@protoc_insertion_point(module_scope)
