# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.grpc import domain_pb2 as domain__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in domain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DomainModelStub(object):
    """The metric and effect model, behind the origin R15 seam.

    Phase 1 ships the flat authored deltas the prototype already has; Phase 4
    replaces the implementation without touching this contract.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Consult = channel.stream_stream(
                '/companyos.domain.v1.DomainModel/Consult',
                request_serializer=domain__pb2.Consultation.SerializeToString,
                response_deserializer=domain__pb2.Effect.FromString,
                _registered_method=True)


class DomainModelServicer(object):
    """The metric and effect model, behind the origin R15 seam.

    Phase 1 ships the flat authored deltas the prototype already has; Phase 4
    replaces the implementation without touching this contract.
    """

    def Consult(self, request_iterator, context):
        """Opened by the kernel, never by this service (R17). The kernel is the gRPC
        client here, which is what keeps the dependency one-directional: no service
        holds the kernel's address, and there is no inbound write entrance to a
        permanent log.

        A bidirectional stream rather than a unary call the kernel awaits, because a
        connection drop is then a *failure signal* rather than a timeout: every
        request outstanding on this stream is known-unanswered, which is exactly what
        recovery needs. A unary call would also put the outstanding-request registry
        in process memory, lost on restart — and R23 requires it to be a projection
        of the log.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DomainModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Consult': grpc.stream_stream_rpc_method_handler(
                    servicer.Consult,
                    request_deserializer=domain__pb2.Consultation.FromString,
                    response_serializer=domain__pb2.Effect.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'companyos.domain.v1.DomainModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('companyos.domain.v1.DomainModel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DomainModel(object):
    """The metric and effect model, behind the origin R15 seam.

    Phase 1 ships the flat authored deltas the prototype already has; Phase 4
    replaces the implementation without touching this contract.
    """

    @staticmethod
    def Consult(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/companyos.domain.v1.DomainModel/Consult',
            domain__pb2.Consultation.SerializeToString,
            domain__pb2.Effect.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
