# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: domain.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'domain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64omain.proto\x12\x13\x63ompanyos.domain.v1\"\xf9\x01\n\x0c\x43onsultation\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\x12\x16\n\x0eraised_at_tick\x18\x03 \x01(\x04\x12\x14\n\x0cperiod_index\x18\x04 \x01(\x04\x12\x13\n\x0bowning_item\x18\x05 \x01(\t\x12?\n\x07metrics\x18\x06 \x03(\x0b\x32..companyos.domain.v1.Consultation.MetricsEntry\x12\x11\n\trules_ver\x18\x07 \x01(\t\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\"\xc2\x01\n\x06\x45\x66\x66\x65\x63t\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x44\n\rmetric_deltas\x18\x02 \x03(\x0b\x32-.companyos.domain.v1.Effect.MetricDeltasEntry\x12\x11\n\trules_ver\x18\x03 \x01(\t\x12\x16\n\x0emodel_identity\x18\x04 \x01(\t\x1a\x33\n\x11MetricDeltasEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x32\\\n\x0b\x44omainModel\x12M\n\x07\x43onsult\x12!.companyos.domain.v1.Consultation\x1a\x1b.companyos.domain.v1.Effect(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'domain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONSULTATION_METRICSENTRY']._loaded_options = None
  _globals['_CONSULTATION_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_EFFECT_METRICDELTASENTRY']._loaded_options = None
  _globals['_EFFECT_METRICDELTASENTRY']._serialized_options = b'8\001'
  _globals['_CONSULTATION']._serialized_start=38
  _globals['_CONSULTATION']._serialized_end=287
  _globals['_CONSULTATION_METRICSENTRY']._serialized_start=241
  _globals['_CONSULTATION_METRICSENTRY']._serialized_end=287
  _globals['_EFFECT']._serialized_start=290
  _globals['_EFFECT']._serialized_end=484
  _globals['_EFFECT_METRICDELTASENTRY']._serialized_start=433
  _globals['_EFFECT_METRICDELTASENTRY']._serialized_end=484
  _globals['_DOMAINMODEL']._serialized_start=486
  _globals['_DOMAINMODEL']._serialized_end=578
# @@protoc_insertion_point(module_scope)
