# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vents.proto\x12\x13\x63ompanyos.events.v1\"\xd8\x01\n\x08\x45nvelope\x12\x0b\n\x03seq\x18\x01 \x01(\x04\x12\x0c\n\x04tick\x18\x02 \x01(\x04\x12,\n\x04kind\x18\x03 \x01(\x0e\x32\x1e.companyos.events.v1.EventKind\x12\x12\n\nschema_ver\x18\x04 \x01(\r\x12\x11\n\trules_ver\x18\x05 \x01(\t\x12\x0f\n\x07payload\x18\x06 \x01(\x0c\x12\x0e\n\x06run_id\x18\x64 \x01(\t\x12\x12\n\ncommand_id\x18\x65 \x01(\t\x12\x12\n\nrequest_id\x18\x66 \x01(\t\x12\x13\n\x0bingested_at\x18g \x01(\t*\xf6\x04\n\tEventKind\x12\x1a\n\x16\x45VENT_KIND_UNSPECIFIED\x10\x00\x12\x0b\n\x07GENESIS\x10\x01\x12\x12\n\x0e\x44\x41Y_CHECKPOINT\x10\x02\x12\x10\n\x0cRATE_CHANGED\x10\x03\x12\x12\n\x0eRUN_TERMINATED\x10\x04\x12\x0e\n\nRUN_FORKED\x10\x05\x12\x13\n\x0fSTORE_RECOVERED\x10\x06\x12\x12\n\x0eREQUEST_RAISED\x10\n\x12\x12\n\x0eINPUT_RECEIVED\x10\x0b\x12\x13\n\x0f\x41NSWER_REJECTED\x10\x0c\x12\r\n\tCEO_INPUT\x10\x14\x12\x15\n\x11\x43HECKPOINT_RAISED\x10\x15\x12\x15\n\x11\x44\x45\x43ISION_RESOLVED\x10\x16\x12\x15\n\x11QUESTION_ANSWERED\x10\x17\x12\x14\n\x10OPTIONS_COMPARED\x10\x18\x12\x19\n\x15\x41UTHORIZATION_DECIDED\x10\x19\x12\x11\n\rWORK_ASSIGNED\x10\x1e\x12\x13\n\x0fWORK_REASSIGNED\x10\x1f\x12\x1c\n\x18WORK_RETURNED_TO_BACKLOG\x10 \x12\x18\n\x14\x44\x45LIVERABLE_PRODUCED\x10!\x12\x11\n\rITEM_UNLOCKED\x10\"\x12\x13\n\x0fMETRICS_APPLIED\x10(\x12\x10\n\x0cLOAD_CHANGED\x10)\x12\x12\n\x0eHIRE_REQUESTED\x10*\x12\x10\n\x0cHIRE_ARRIVED\x10+\x12\x10\n\x0cHIRE_REFUSED\x10,\x12\r\n\tATTRITION\x10-\x12\x17\n\x13\x44\x41ILY_COSTS_APPLIED\x10.\x12\x14\n\x10\x43OMMAND_REJECTED\x10\x32\x12\x0f\n\x0bSTAFF_MOVED\x10<b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTKIND']._serialized_start=257
  _globals['_EVENTKIND']._serialized_end=887
  _globals['_ENVELOPE']._serialized_start=38
  _globals['_ENVELOPE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
