# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts.grpc import events_pb2 as events__pb2
from contracts.grpc import kernel_pb2 as kernel__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kernel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KernelStub(object):
    """The kernel's inbound surface. The gateway is its only caller.

    Note the direction of everything here: callers come *to* the kernel. The
    kernel's own outbound calls — to the domain and agent services — are streams it
    opens itself, defined in domain.proto and agents.proto. The kernel therefore has
    no outbound dependency on any read-side service (R17), and nothing outside it
    holds a write entrance to the log.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitCommand = channel.unary_unary(
                '/companyos.kernel.v1.Kernel/SubmitCommand',
                request_serializer=kernel__pb2.Command.SerializeToString,
                response_deserializer=kernel__pb2.CommandOutcome.FromString,
                _registered_method=True)
        self.CommandOutcomeByKey = channel.unary_unary(
                '/companyos.kernel.v1.Kernel/CommandOutcomeByKey',
                request_serializer=kernel__pb2.OutcomeByKeyRequest.SerializeToString,
                response_deserializer=kernel__pb2.CommandOutcome.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/companyos.kernel.v1.Kernel/SubscribeEvents',
                request_serializer=kernel__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=events__pb2.Envelope.FromString,
                _registered_method=True)
        self.Fold = channel.unary_unary(
                '/companyos.kernel.v1.Kernel/Fold',
                request_serializer=kernel__pb2.FoldRequest.SerializeToString,
                response_deserializer=kernel__pb2.FoldResponse.FromString,
                _registered_method=True)
        self.Replay = channel.unary_unary(
                '/companyos.kernel.v1.Kernel/Replay',
                request_serializer=kernel__pb2.ReplayRequest.SerializeToString,
                response_deserializer=kernel__pb2.ReplayResponse.FromString,
                _registered_method=True)
        self.Fork = channel.unary_unary(
                '/companyos.kernel.v1.Kernel/Fork',
                request_serializer=kernel__pb2.ForkRequest.SerializeToString,
                response_deserializer=kernel__pb2.ForkResponse.FromString,
                _registered_method=True)
        self.ExportRun = channel.unary_unary(
                '/companyos.kernel.v1.Kernel/ExportRun',
                request_serializer=kernel__pb2.ExportRequest.SerializeToString,
                response_deserializer=kernel__pb2.ExportResponse.FromString,
                _registered_method=True)
        self.Diagnose = channel.unary_unary(
                '/companyos.kernel.v1.Kernel/Diagnose',
                request_serializer=kernel__pb2.DiagnoseRequest.SerializeToString,
                response_deserializer=kernel__pb2.DiagnoseResponse.FromString,
                _registered_method=True)


class KernelServicer(object):
    """The kernel's inbound surface. The gateway is its only caller.

    Note the direction of everything here: callers come *to* the kernel. The
    kernel's own outbound calls — to the domain and agent services — are streams it
    opens itself, defined in domain.proto and agents.proto. The kernel therefore has
    no outbound dependency on any read-side service (R17), and nothing outside it
    holds a write entrance to the log.
    """

    def SubmitCommand(self, request, context):
        """Enqueued for a tick boundary; the response reports the outcome rather than
        mere acceptance. Validating and applying in separate steps would leave a race
        where a command validates against a state the tick then changes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommandOutcomeByKey(self, request, context):
        """R30: retry is expected behaviour for a call whose response the client may
        never have seen, so a reconnecting client resolves an in-flight command by
        key instead of retrying blind.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Read-only, and with no effect on simulation state. Subscribing does not start
        a clock: tick-loop lifecycle follows the run's persisted rate (R18), because
        starting on subscribe would race two loops into existence on near-simultaneous
        subscribes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fold(self, request, context):
        """Fold a log prefix to state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replay(self, request, context):
        """Historical replay. Never re-issues an external call: it reads the logged
        answer (R3).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fork(self, request, context):
        """Take a past decision differently, and get a run back for it. Committed
        inside the lease-fenced transaction — the only path that satisfies both the
        lease and the sole-appender rule, which is why it is not a free-standing
        store operation.

        Its own method rather than a CommandKind, for the reason run creation is its
        own verb: a command must never bring a simulation into being. See FORK_RUN
        below.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportRun(self, request, context):
        """R32: a run leaves the machine as a self-contained artifact.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Diagnose(self, request, context):
        """Answers "why did the clock stop" without anyone reading a log. The
        highest-leverage diagnostic in the system.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KernelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitCommand,
                    request_deserializer=kernel__pb2.Command.FromString,
                    response_serializer=kernel__pb2.CommandOutcome.SerializeToString,
            ),
            'CommandOutcomeByKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CommandOutcomeByKey,
                    request_deserializer=kernel__pb2.OutcomeByKeyRequest.FromString,
                    response_serializer=kernel__pb2.CommandOutcome.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=kernel__pb2.SubscribeRequest.FromString,
                    response_serializer=events__pb2.Envelope.SerializeToString,
            ),
            'Fold': grpc.unary_unary_rpc_method_handler(
                    servicer.Fold,
                    request_deserializer=kernel__pb2.FoldRequest.FromString,
                    response_serializer=kernel__pb2.FoldResponse.SerializeToString,
            ),
            'Replay': grpc.unary_unary_rpc_method_handler(
                    servicer.Replay,
                    request_deserializer=kernel__pb2.ReplayRequest.FromString,
                    response_serializer=kernel__pb2.ReplayResponse.SerializeToString,
            ),
            'Fork': grpc.unary_unary_rpc_method_handler(
                    servicer.Fork,
                    request_deserializer=kernel__pb2.ForkRequest.FromString,
                    response_serializer=kernel__pb2.ForkResponse.SerializeToString,
            ),
            'ExportRun': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportRun,
                    request_deserializer=kernel__pb2.ExportRequest.FromString,
                    response_serializer=kernel__pb2.ExportResponse.SerializeToString,
            ),
            'Diagnose': grpc.unary_unary_rpc_method_handler(
                    servicer.Diagnose,
                    request_deserializer=kernel__pb2.DiagnoseRequest.FromString,
                    response_serializer=kernel__pb2.DiagnoseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'companyos.kernel.v1.Kernel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('companyos.kernel.v1.Kernel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Kernel(object):
    """The kernel's inbound surface. The gateway is its only caller.

    Note the direction of everything here: callers come *to* the kernel. The
    kernel's own outbound calls — to the domain and agent services — are streams it
    opens itself, defined in domain.proto and agents.proto. The kernel therefore has
    no outbound dependency on any read-side service (R17), and nothing outside it
    holds a write entrance to the log.
    """

    @staticmethod
    def SubmitCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companyos.kernel.v1.Kernel/SubmitCommand',
            kernel__pb2.Command.SerializeToString,
            kernel__pb2.CommandOutcome.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommandOutcomeByKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companyos.kernel.v1.Kernel/CommandOutcomeByKey',
            kernel__pb2.OutcomeByKeyRequest.SerializeToString,
            kernel__pb2.CommandOutcome.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/companyos.kernel.v1.Kernel/SubscribeEvents',
            kernel__pb2.SubscribeRequest.SerializeToString,
            events__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companyos.kernel.v1.Kernel/Fold',
            kernel__pb2.FoldRequest.SerializeToString,
            kernel__pb2.FoldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Replay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companyos.kernel.v1.Kernel/Replay',
            kernel__pb2.ReplayRequest.SerializeToString,
            kernel__pb2.ReplayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companyos.kernel.v1.Kernel/Fork',
            kernel__pb2.ForkRequest.SerializeToString,
            kernel__pb2.ForkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companyos.kernel.v1.Kernel/ExportRun',
            kernel__pb2.ExportRequest.SerializeToString,
            kernel__pb2.ExportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Diagnose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/companyos.kernel.v1.Kernel/Diagnose',
            kernel__pb2.DiagnoseRequest.SerializeToString,
            kernel__pb2.DiagnoseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
