/**
 * Frames for the suites, built from the *real* genesis payload.
 *
 * `backend/tests/fixtures/golden/genesis.json` is generated by the kernel, so these tests
 * parse the shape the kernel actually sends. A hand-typed genesis fixture would be a second
 * opinion about the very shape it exists to pin, and the two would drift the first time a
 * field was added — which is exactly what happened when `catalog`, `metric_defs` and `load`
 * arrived with U13 and U14. Reading the generated file means the suite fails when the payload
 * changes, which is the point.
 *
 * A missing fixture is a failure rather than a skip, for the same reason `golden.test.ts`
 * treats it that way: a skipped fixture test reports green while nothing is checked.
 */

import { existsSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import type { CatalogEntry, EventFrame } from '../../src/net/store'

const HERE = dirname(fileURLToPath(import.meta.url))
const GOLDEN = join(HERE, '..', '..', '..', 'backend', 'tests', 'fixtures', 'golden')

export interface GenesisFixture {
  kind: string
  payload: Record<string, unknown>
}

let cached: GenesisFixture | null = null

/** The generated genesis payload. Throws rather than skipping if it has not been generated. */
export function genesisFixture(): GenesisFixture {
  if (cached !== null) return cached

  const path = join(GOLDEN, 'genesis.json')
  if (!existsSync(path)) {
    throw new Error(
      `golden fixture genesis.json is missing from ${GOLDEN}. Regenerate it with ` +
        '`cd backend && uv run python scripts/generate_golden.py`. This is a failure, not a ' +
        'skip: a skipped fixture test reports green while nothing is being checked.',
    )
  }

  cached = JSON.parse(readFileSync(path, 'utf8')) as GenesisFixture
  assertFixtureIsCurrent(cached)
  return cached
}

/**
 * The fields the client's own types say a catalog option carries.
 *
 * Missing is not the same as absent-by-design: `tacit` is withheld on purpose and is asserted
 * absent elsewhere, while these three are the payload's current shape. A fixture predating
 * them parses fine and renders nothing, so without this check the suite would report green
 * while every option's consequence was silently empty.
 */
const OPTION_FIELDS = ['label', 'detail', 'effect', 'draw_delta', 'note'] as const

const REGENERATE =
  'Regenerate it with `cd backend && uv run python scripts/generate_golden.py`. This is a ' +
  'failure, not a skip: a stale fixture parses cleanly and renders nothing, so the suite ' +
  'would report green while nothing was being checked.'

export function assertFixtureIsCurrent(fixture: GenesisFixture): void {
  const catalog = fixture.payload.catalog
  if (!Array.isArray(catalog) || catalog.length === 0) {
    throw new Error(`golden fixture genesis.json carries no catalog. ${REGENERATE}`)
  }

  for (const entry of catalog as CatalogEntry[]) {
    for (const checkpoint of entry.checkpoints ?? []) {
      for (const option of checkpoint.options ?? []) {
        for (const field of OPTION_FIELDS) {
          if (!(field in option)) {
            throw new Error(
              `golden fixture genesis.json is stale: an option on ${entry.id} has no ` +
                `${field}. ${REGENERATE}`,
            )
          }
        }
      }
    }
  }
}

/**
 * The authored work graph, straight off the fixture.
 *
 * Typed as the store's own `CatalogEntry` rather than as a hand-listed subset. The fixture *is*
 * that payload, so a narrower local shape only means a suite that reads a real field has to
 * cast around its own helper — and the cast is where a genuine shape change would go unnoticed.
 */
export function catalogFixture(): CatalogEntry[] {
  return genesisFixture().payload.catalog as CatalogEntry[]
}

export function metricDefsFixture(): Array<{ key: string; good: number; display_max: number }> {
  return genesisFixture().payload.metric_defs as never
}

/** The GENESIS event, as the gateway would frame it. */
export function genesisFrame(seq = 1): EventFrame {
  const fixture = genesisFixture()
  return {
    kind: 'GENESIS',
    seq: String(seq),
    tick: '0',
    schema_ver: 2,
    rules_ver: String(fixture.payload.rules_ver ?? 'test'),
    run_id: 'run-1',
    command_id: '',
    request_id: '',
    payload: fixture.payload,
  }
}

/** A metrics-bearing event, for driving the HUD. */
export function metricsFrame(options: {
  seq: number
  tick?: number
  cash?: number
  manualHours?: number
  leadTime?: number
  morale?: number
  visibility?: number
  deltas?: Record<string, number>
}): EventFrame {
  const metrics: Record<string, number> = {
    cash: options.cash ?? 4800,
    manualHours: options.manualHours ?? 340,
    leadTime: options.leadTime ?? 12,
    morale: options.morale ?? 72,
    visibility: options.visibility ?? 6,
  }

  return {
    kind: 'DAILY_COSTS_APPLIED',
    seq: String(options.seq),
    tick: String(options.tick ?? 540),
    schema_ver: 1,
    rules_ver: 'test',
    run_id: 'run-1',
    command_id: '',
    request_id: '',
    payload: {
      tick: options.tick ?? 540,
      day: 1,
      total_cost: 20,
      metrics,
      deltas: options.deltas ?? {},
    },
  }
}

/**
 * An event that moves one item to one status.
 *
 * Built around `item_status`, which every item-moving event now carries. The client reads it
 * rather than inferring status from the event kind, so a test that moves an item through all
 * five states is a test of the projection and not of a mapping table.
 */
export function itemFrame(options: {
  seq: number
  kind: string
  item: string
  status: string
  tick?: number
  person?: string
  cpIndex?: number
  label?: string
}): EventFrame {
  return {
    kind: options.kind,
    seq: String(options.seq),
    tick: String(options.tick ?? 600),
    schema_ver: 2,
    rules_ver: 'test',
    run_id: 'run-1',
    command_id: '',
    request_id: '',
    payload: {
      tick: options.tick ?? 600,
      item: options.item,
      item_status: options.status,
      person: options.person ?? 'stf_ap',
      cp_index: options.cpIndex ?? 0,
      label: options.label ?? 'Information',
      kind: 'info',
    },
  }
}

/** A load map for every reporting line the fixture's roster carries. */
export function loadFrame(options: {
  seq: number
  load: Record<string, number>
  tick?: number
}): EventFrame {
  return {
    kind: 'LOAD_CHANGED',
    seq: String(options.seq),
    tick: String(options.tick ?? 600),
    schema_ver: 1,
    rules_ver: 'test',
    run_id: 'run-1',
    command_id: '',
    request_id: '',
    payload: { tick: options.tick ?? 600, load: options.load },
  }
}

/**
 * A recording 2D context.
 *
 * jsdom does not implement `getContext`, and standing up a real canvas to check that a blocked
 * node drew violet would test the canvas implementation rather than the encoding. Every drawing
 * path in the client takes its context as a parameter for this reason: the properties worth
 * asserting are "which colour, on which form, at which size", and those are statements about
 * draw calls.
 */
export interface Recorded {
  x: number
  y: number
  width: number
  height: number
  fill: string
}

export class RecordingContext {
  fillStyle: string = '#000000'
  readonly rects: Recorded[] = []

  fillRect(x: number, y: number, width: number, height: number): void {
    this.rects.push({ x, y, width, height, fill: String(this.fillStyle) })
  }

  /** Every distinct colour drawn, which is what a hue assertion reads. */
  colours(): Set<string> {
    return new Set(this.rects.map((rect) => rect.fill))
  }

  /** Only the rectangles drawn in one colour. */
  inColour(colour: string): Recorded[] {
    return this.rects.filter((rect) => rect.fill === colour)
  }

  /**
   * A shape signature that ignores colour entirely.
   *
   * This is how "the five states remain distinguishable with every status hue replaced by one
   * value" is checked: flatten the colour out and compare what is left. If two states have the
   * same signature, the encoding was carrying the distinction in hue alone.
   */
  geometry(): string {
    return this.rects.map((rect) => `${rect.x},${rect.y},${rect.width},${rect.height}`).join(';')
  }

  clear(): void {
    this.rects.length = 0
  }
}
